name: Healthcheck

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://pokedexpractice.herokuapp.com/health"
          max-attempts: 3
          retry-delay: 10s
