name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  print_date_and_dir:
    runs-on: ubuntu-18.04
    steps:
      - name: Print date
      run: date
      - name: Print directory info
      run: ls -l

